/** Agent 工具名 → 中文显示名 */
export const TOOL_NAMES: Record<string, string> = {
  // 内置工具
  search_articles: '搜索文章',
  get_article: '获取全文',
  get_categories: '查看分类',
  recommend_articles: '推荐文章',
  search_web: '联网搜索',
  read_url: '读取网页',
  get_recent_articles: '最新文章',
  create_draft: '创建草稿',
  update_article: '编辑文章',
  list_drafts: '列出草稿',
  set_status: '发布/下架',
  delete_article: '删除文章',
  make_mindmap: '思维导图',
  read_document: '阅读文档',
  summarize_url: 'AI 摘要',
  summarize_text: 'AI 摘要',
  export_file: '导出文件',
  generate_presentation: '生成PPT幻灯片',
  generate_weekly_video: '生成周报视频',
  extract_images: '提取网页图片',

  // MCP 工具
  mcp_markmap__markdown_to_mindmap: '思维导图(MCP)',
  mcp_bazi__bazi: '八字算命',
  mcp_bazi__wuxing: '五行查询',
  mcp_bazi__shengxiao: '生肖查询',
  mcp_amap__geo: '地理编码',
  mcp_amap__regeo: '逆地理编码',
  mcp_amap__ip: 'IP 定位',
  mcp_amap__weather: '天气查询',
  mcp_amap__direction_walking: '步行路线',
  mcp_amap__direction_bicycling: '骑行路线',
  mcp_amap__direction_driving: '驾车路线',
  mcp_amap__direction_transit: '公交路线',
  mcp_amap__distance: '距离测量',
  mcp_amap__text_search: '地点搜索',
  mcp_amap__around_search: '周边搜索',
  mcp_amap__search_detail: '地点详情',
  mcp_amap__district: '行政区划',
  mcp_amap__assistant: '地图问答',
  mcp_amap__maps_weather: '天气查询',
  mcp_amap__maps_geo: '地理编码',
  mcp_amap__maps_regeo: '逆地理编码',
  mcp_amap__maps_ip_location: 'IP 定位',
  mcp_amap__maps_bicycling: '骑行路线',
  mcp_amap__maps_direction_walking: '步行路线',
  mcp_amap__maps_direction_driving: '驾车路线',
  mcp_amap__maps_direction_transit: '公交路线',
  mcp_amap__maps_distance: '距离测量',
  mcp_amap__maps_text_search: '地点搜索',
  mcp_amap__maps_around_search: '周边搜索',
  mcp_amap__maps_search_detail: '地点详情',
  mcp_amap__maps_config_district: '行政区划',
  mcp_deepwiki__read_wikipedia: '维基百科',
  mcp_feishu__getWikiDoc: '飞书知识库读取',
  mcp_feishu__getDocx: '飞书文档读取',
  mcp_filesystem__read_file: '读取文件',
  mcp_filesystem__write_file: '写入文件',
  mcp_filesystem__list_directory: '列出目录',
  mcp_filesystem__create_directory: '创建目录',
  mcp_filesystem__move_file: '移动文件',
  mcp_filesystem__search_files: '搜索文件',
  mcp_filesystem__get_file_info: '文件信息',
  mcp_filesystem__list_allowed_directories: '允许目录',
  mcp_filesystem__edit_file: '编辑文件',
};